---
- hosts: localhost

  vars:
    work_dir: "/var/tmp"
    base_url: "https://"

  tasks:
#    - get_url: url={{ base_url }}/{{ item.name }} dest={{ work_dir }} sha256sum={{ item.sha256sum }} force=yes
#      with_items:
#        - {name: "", sha256sum: ""}

#    - copy: src={{ work_dir }} dst=bb

#    - template: src={{ work_dir }}/{{ item }} dest=/dst/{{ item }} owner=root group=root mode=0644
#      with_items:
#        - pd-handler-uart
#        - ssh

    - git: repo=https://github.com/ma2shita/obsiot_ansible_dist.git dest=/srv/reset/ version=2016-0312_handson
    - file: path=/srv/reset/reset_bx1.sh mode=0755
#    - service: name=openblocks-iot-webui enabled=yes

#    - command: halt
#EoPlaybook
