---
- hosts: localhost

  vars:
    work_dir: "/var/tmp"
    base_url: "https://github.com/ma2shita/obsiot_ansible_dist/raw/2016-0312_handson"

  tasks:
    - name: Report to FrightBoard
      uri:
        url: "http://conf.local:3000/api/v1/statuses?iid={{host_id}}"
        body: ""
        method: POST
        timeout: 3
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        status_code: 200,201
      ignore_errors: True

    - get_url: url=http://ftp.jp.debian.org/debian/pool/main/j/jq/jq_1.4-1~bpo70+1_i386.deb dest={{ work_dir }} sha256sum=eba3b4465e923f362eb8e612550ac1f6e93dc749f94163b9a831db69d705f36f force=yes
    - apt: deb={{ work_dir }}/jq_1.4-1~bpo70+1_i386.deb

    - apt: name=python-apt
    - apt_key: url=http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
    - apt_repository: repo='deb http://repo.mosquitto.org/debian wheezy main'
    - apt: name=mosquitto-clients

    - get_url: url="https://drive.google.com/uc?export=download&id=0B8oVjSSLpXBLYUlEa2pJbjRxUUk" dest={{ work_dir }}/mabeeedemo-i386 sha256sum=cece92e953e1f3ec17790bbdd7b98499dd8cbe9ea25135229e542ef4e743b35f force=yes
    - copy: src={{ work_dir }}/mabeeedemo-i386 dest=/usr/local/bin/mabeeedemo owner=root group=root mode=0755

    - get_url: url={{ base_url }}/patch_for_1.0.7/{{ item.name }} dest={{ work_dir }} sha256sum={{ item.sha256sum }} force=yes
      with_items:
        - {name: "appliance.sh.diff",     sha256sum: "9fb4a71e93d31ca24426b441d9b8d20d274117cb0950ebc74c5312dbef6c498b"}
        - {name: "fwm8blz02-es1.js.diff", sha256sum: "f8b877d3ea7a2b5eb3380e0853f724dda0089d160d8234a6a4d35e459a5e1cc9"}

    - patch: src={{ work_dir }}/appliance.sh.diff     basedir=/var/webui/bin
    - patch: src={{ work_dir }}/fwm8blz02-es1.js.diff basedir=/opt/pd/handler/node_modules/fsensor/lib

    - file: path=/srv/reset/ state=absent
    - git: repo=https://github.com/ma2shita/obsiot_ansible_dist.git dest=/srv/reset/ version=2016-0312_handson
    - file: path=/srv/reset/reset_bx1.sh mode=0755

    - shell: echo "autostart = false" >> /etc/supervisor/conf.d/setup_by_ansible.conf
    - service: name=openblocks-iot-webui enabled=yes

    - name: Report to FrightBoard
      uri:
        url: "http://conf.local:3000/api/v1/statuses?iid={{host_id}}"
        body: "status=completed"
        method: POST
        timeout: 3
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        status_code: 200,201
      ignore_errors: True

    - command: halt
#EoPlaybook
