---
- hosts: localhost

  vars:
    work_dir: "/var/tmp"
    base_url: "https://github.com/ma2shita/obsiot_ansible_dist/raw/2016-0312_handson"

  tasks:
    - get_url: url={{ base_url }}/patch_for_1.0.7/{{ item.name }} dest={{ work_dir }} sha256sum={{ item.sha256sum }} force=yes
      with_items:
        - {name: "appliance.sh.diff",     sha256sum: "9fb4a71e93d31ca24426b441d9b8d20d274117cb0950ebc74c5312dbef6c498b"}
        - {name: "fwm8blz02-es1.js.diff", sha256sum: "f8b877d3ea7a2b5eb3380e0853f724dda0089d160d8234a6a4d35e459a5e1cc9"}

    - patch: src={{ work_dir }}/appliance.sh.diff     basedir=/var/webui/bin
    - patch: src={{ work_dir }}/fwm8blz02-es1.js.diff basedir=/opt/pd/handler/node_modules/fsensor/lib

    - file: path=/srv/reset/ state=absent
    - git: repo=https://github.com/ma2shita/obsiot_ansible_dist.git dest=/srv/reset/ version=2016-0312_handson
    - file: path=/srv/reset/reset_bx1.sh mode=0755

    - shell: echo "autostart = false" >> /etc/supervisor/conf.d/setup_by_ansible.conf
    - service: name=openblocks-iot-webui enabled=yes
    - command: halt
#EoPlaybook
